spring:
  application:
    name: "cruncher"
  datasource:
    #    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost/sysco_oms"
    username: root
    password: root

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 100
      order_updates: true
      batch_versioned_data: true

server:
  port: 8081
